name: Branch Created

on:
  create:
    branches:
      - '**'

jobs:
  notify-on-branch-create:
    runs-on: ubuntu-latest
    if: github.ref_type == 'branch'
    steps:
      - name: Notify about branch
        run: echo "New branch created: ${{ github.ref }}"

